CREATE TABLE BOOKS
(
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE           VARCHAR(255) NOT NULL,
    AUTHOR          VARCHAR(255) NOT NULL,
    DESCRIPTION     VARCHAR(255) NOT NULL,
    GENRE           VARCHAR(255) NOT NULL,
    LENGTH          BIGINT       NOT NULL,
    PRICE           BIGINT       NOT NULL,
    COMMENT         VARCHAR(255) NOT NULL,
    CREATE_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);